#:schema node_modules/wrangler/config-schema.json
name = "misskey-webhook-to-discord"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "1091c85365ab4b588f595adb5d136f66"
